vim.keymap.set('n', '<F1>', function()
  local lines = {
    'Dotfiles Neovim — keep this buffer open or press q to close',
    '',
    '=== The ":" commands (command-line mode) ===',
    'Type Shift + ; to get ":" at the bottom, then the words, then Enter.',
    '',
    '  Quit nvim completely     :qa    then Enter',
    '  Save current file        :w     then Enter',
    '  Download/fix plugins     :Lazy sync    then Enter   (needs internet)',
    '',
    '=== Normal mode (press Escape to get here) ===',
    '  File browser (here)       minus key  -',
    '  File browser              Space  e  m   (same as Space e e; Space e f = cwd)',
    '  Docked Oil sidebar + preview   Space  e  s (buffer dir)   Space  e  Shift+s (cwd)',
    '  Find file by name         Space  f  f   (Space is the big key; pause after Space)',
    '  Search text in folder     Space  f  g',
    '  Jump windows              Ctrl-h / Ctrl-l (hold Ctrl)',
    '',
    '=== Oil.nvim — docked sidebar (your permanent explorer + preview) ===',
    'Open / close:',
    '  Space e s          Toggle sidebar at directory of current file + vertical preview',
    '  Space e Shift+s    Same, but start at Neovim cwd (vim.fn.getcwd)',
    '  q                  In Oil: if focus is the sidebar window, closes sidebar + preview;',
    '                     otherwise closes that Oil buffer only.',
    'Layout: narrow listing (winfixwidth) | preview pane | your editor. Toggle again to dismiss.',
    '',
    'Movement & opening (normal mode in Oil buffer):',
    '  l or Enter         Open entry (file opens in existing window; dir drills down)',
    '  h or -             Go to parent directory',
    '  Ctrl+s             Open in vertical split',
    '  Ctrl+h             Open in horizontal split',
    '  Ctrl+t             Open in new tab',
    '  Ctrl+p             Toggle preview window (sidebar mode already uses live preview)',
    '  Ctrl+l             Refresh listing',
    '  Ctrl+c             Close Oil buffer',
    '',
    'Directories & scope:',
    '  _                  Jump Oil to cwd',
    '  `                  cd Neovim cwd to directory under cursor',
    '  g~                 cd for current tab only (scope tab)',
    '',
    'Visibility & trash:',
    '  g.                 Toggle hidden (dotfiles)',
    '  g\\                Toggle trash view (oil-trash scheme)',
    '',
    'Other:',
    '  gs                 Change sort',
    '  gx                 Open with external app (xdg-open / open)',
    '  g?                 Floating help with all Oil keymaps',
    '',
    ':Oil command (same plugin; optional alternative to Space e s):',
    '  :Oil                  Open Oil (float=false) for cwd / optional path',
    '  :Oil path/to/dir      Open that directory',
    '  :Oil --float          Floating Oil',
    '  :Oil --preview        Open with preview (split layout decided by Oil)',
    '  :Oil --trash          Trash browser',
    '  :Oil --progress       Restore progress UI if a rename/delete batch is running',
    '  :vertical Oil …       :split modifiers combine with :Oil (see :help :vertical)',
    'Full actions list:      :help oil-actions',
    '',
    'Editing the filesystem:',
    'Oil buffers are normal buffers: rename/create/delete like text; save with :w to apply.',
    'delete_to_trash is on — deletes use system trash when supported.',
    '',
    '=== File browser — telescope-file-browser (flat list, not a tree) ===',
    '  One folder at a time: the list IS the current directory only (no expand-in-place tree).',
    '  Open file or move into a folder      l   or Enter',
    '  Parent folder                       h   (normal mode in the picker)',
    '  More actions                         ?   inside the picker',
    '  :edit path/to/dir opens this picker (hijack_netrw). No Neo-tree sidebar.',
    '  Close                                Esc or q',
    '',
    '=== Agentic.nvim (ACP chat) — Neovim 0.11+; provider: Cursor (cursor-agent acp) ===',
    '  Toggle chat               Ctrl + \\',
    '  Add file / selection      Ctrl + \'',
    '  New session               Ctrl + ,',
    '  Restore session           Alt + i   then r',
    '  Switch provider / model     \\ then s / \\ then m (maplocalleader; see :help maplocalleader)',
    '  Diagnostics → context     Space  a  d  / Space  a  D',
    '  CLI: cursor agent login  ~  same account as cursor-agent; docs: github.com/carlos-algms/agentic.nvim',
    '',
    '=== Cursor Agent CLI (terminal agent — pairs with same repos you edit in Neovim) ===',
    'Install / PATH: ships with Cursor.app; ensure `cursor` is on PATH (CLI tab in Cursor settings).',
    '',
    'First-time auth (interactive):',
    '  cursor agent login              Browser login; stores auth for the CLI',
    '  cursor agent whoami             Confirm account',
    '  cursor agent logout             Clear CLI auth',
    '',
    'Shell integration (optional — adds helpers to ~/.zshrc):',
    '  cursor agent install-shell-integration',
    '  cursor agent uninstall-shell-integration',
    '',
    'Typical interactive session (run from your git repo root):',
    '  cd /path/to/project',
    '  cursor agent                    Start TUI agent (cwd = workspace)',
    '  cursor agent "your prompt"      Start with an initial message',
    '',
    'Headless / scripts (non-interactive):',
    '  cursor agent --print --trust "Summarize src/"',
    '  cursor agent -p --workspace /path/to/repo --output-format text "task"',
    '  --mode plan | --plan      Read-only planning',
    '  --mode ask                Read-only Q&A',
    '  --force | --yolo          Auto-approve tools (use carefully)',
    '  --sandbox enabled|disabled Override sandbox',
    '  --api-key …  or  CURSOR_API_KEY   Auth for CI/automation',
    '  --resume [chatId]  /  cursor agent resume   Continue sessions',
    '',
    'Workspace = what the agent can read/write: match Neovim cwd or repo root:',
    '  cursor agent --workspace ~/projects/myrepo "refactor X"',
    'Oil Space e Shift+s opens sidebar at Neovim cwd — keep cwd aligned with --workspace.',
    'Agent and Neovim are separate: the CLI edits files on disk; reload buffers (:e) if needed.',
    '',
    'CLI preferences (~/.cursor/cli-config.json):',
    '  permissions.allow / permissions.deny   Tool patterns (e.g. Shell(**), Mcp(...))',
    '  approvalMode                           allowlist vs unrestricted',
    '  editor.vimMode                         Vim keys in CLI input',
    '  sandbox.*                            Default sandbox / network',
    'Project overrides: .cursor/cli.json from git root → cwd merged per session.',
    '',
    'MCP from CLI:',
    '  cursor agent mcp …                   Manage MCP servers for agent',
    '  cursor --add-mcp \'{"name":…}\'      Add MCP JSON to profile/workspace',
    '',
    'More:',
    '  cursor agent models                  List models',
    '  cursor agent update                  Update agent binary',
    '  cursor agent --help                  All flags',
    '',
    '=== About "lazy load" ===',
    'You do not need to manage it. Some tools load the first time you use them.',
    'If colors or Space-f-f feel broken, run :Lazy sync once and restart nvim.',
  }
  local buf = vim.api.nvim_create_buf(false, true)
  vim.bo[buf].buftype = 'nofile'
  vim.bo[buf].bufhidden = 'wipe'
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
  local w = math.min(76, vim.o.columns - 4)
  local h = math.min(#lines + 2, vim.o.lines - 4)
  vim.api.nvim_open_win(buf, true, {
    relative = 'editor',
    width = w,
    height = h,
    row = math.max(0, math.floor((vim.o.lines - h) / 2)),
    col = math.max(0, math.floor((vim.o.columns - w) / 2)),
    style = 'minimal',
    border = 'rounded',
    title = ' Help ',
    title_pos = 'center',
  })
  vim.keymap.set('n', 'q', '<cmd>close<cr>', { buffer = buf, silent = true })
end, { desc = 'Dotfiles nvim cheat sheet' })
